#!/bin/bash
# Prépare les fichiers pour l'upload Supabase Storage.
# Crée un dossier _upload/ avec les fichiers renommés proprement.
# Usage: bash scripts/prepare-uploads.sh

DRIVE="/Users/belkheirbekhedda/Library/CloudStorage/GoogleDrive-belkheirb@icloud.com/Mon Drive"
OUT="$DRIVE/_upload"

echo "📁 Création du dossier de sortie..."
mkdir -p "$OUT"

copy() {
  local src="$1"
  local dest="$2"
  mkdir -p "$(dirname "$dest")"
  if [ -f "$src" ]; then
    cp "$src" "$dest"
    echo "  ✓ $(basename "$dest")"
  else
    echo "  ✗ MANQUANT: $src"
  fi
}

# ─── FRONT OFFICE ────────────────────────────────────────────────────────────
echo ""
echo "📘 Front Office..."

FO_PDF_FR="$DRIVE/Playbook FO/PDF/FR"
FO_PDF_EN="$DRIVE/Playbook FO/PDF/EN"
FO_PPT_FR="$DRIVE/Playbook FO/PPT/FR"
FO_PPT_EN="$DRIVE/Playbook FO/PPT/EN"

copy "$FO_PDF_FR/Chapitre 1 - Introduction au manuel des procédures du front office.pdf"  "$OUT/front-office/pdf/fr/ch01-introduction.pdf"
copy "$FO_PDF_FR/Chapitre 2 - Procédure de check-in.pdf"                                  "$OUT/front-office/pdf/fr/ch02-check-in.pdf"
copy "$FO_PDF_FR/Chapitre 3 - Procédure de check-out.pdf"                                 "$OUT/front-office/pdf/fr/ch03-check-out.pdf"
copy "$FO_PDF_FR/Chapitre 4 - Communication client.pdf"                                   "$OUT/front-office/pdf/fr/ch04-communication-client.pdf"
copy "$FO_PDF_FR/Chapitre 5 - Techniques d'upselling.pdf"                                 "$OUT/front-office/pdf/fr/ch05-upselling.pdf"
copy "$FO_PDF_FR/Chapitre 6 - Systèmes et opérations PMS.pdf"                             "$OUT/front-office/pdf/fr/ch06-pms.pdf"
copy "$FO_PDF_FR/Chapitre 7 - Night Audit.pdf"                                            "$OUT/front-office/pdf/fr/ch07-night-audit.pdf"
copy "$FO_PDF_FR/Chapitre 8 - Management de l'équipe.pdf"                                 "$OUT/front-office/pdf/fr/ch08-management.pdf"
copy "$FO_PDF_FR/Chapitre 9 - Procédures d'urgence.pdf"                                   "$OUT/front-office/pdf/fr/ch09-urgence.pdf"
copy "$FO_PDF_FR/Chapitre 10 - Excellence et normes de qualité.pdf"                       "$OUT/front-office/pdf/fr/ch10-excellence.pdf"
copy "$FO_PDF_FR/Chapitre 11 - Concierge et services clients.pdf"                         "$OUT/front-office/pdf/fr/ch11-concierge.pdf"
copy "$FO_PDF_FR/Chapitre 12 - Bagagistes et portiers.pdf"                                "$OUT/front-office/pdf/fr/ch12-bagagistes.pdf"

copy "$FO_PDF_EN/Chapter 1 - Introduction.pdf"                                            "$OUT/front-office/pdf/en/ch01-introduction.pdf"
copy "$FO_PDF_EN/Chapter 2 - Check-in Procedure.pdf"                                      "$OUT/front-office/pdf/en/ch02-check-in.pdf"
copy "$FO_PDF_EN/Chapter 3 - Check-out Procedure.pdf"                                     "$OUT/front-office/pdf/en/ch03-check-out.pdf"
copy "$FO_PDF_EN/Chapter 4 - Guest Communication.pdf"                                     "$OUT/front-office/pdf/en/ch04-guest-communication.pdf"
copy "$FO_PDF_EN/Chapter 5 - Upselling Techniques.pdf"                                    "$OUT/front-office/pdf/en/ch05-upselling.pdf"
copy "$FO_PDF_EN/Chapter 6 - Systems and PMS Operations.pdf"                              "$OUT/front-office/pdf/en/ch06-pms.pdf"
copy "$FO_PDF_EN/Chapter 7 - Night Audit.pdf"                                             "$OUT/front-office/pdf/en/ch07-night-audit.pdf"
copy "$FO_PDF_EN/Chapter 8 - Team Management.pdf"                                         "$OUT/front-office/pdf/en/ch08-management.pdf"
copy "$FO_PDF_EN/Chapter 9 - Emergency Procedures.pdf"                                    "$OUT/front-office/pdf/en/ch09-emergency.pdf"
copy "$FO_PDF_EN/Chapter 10 - Excellence and Quality Standards.pdf"                       "$OUT/front-office/pdf/en/ch10-excellence.pdf"
copy "$FO_PDF_EN/Chapter 11 - Concierge and Guest Services.pdf"                           "$OUT/front-office/pdf/en/ch11-concierge.pdf"
copy "$FO_PDF_EN/Chapter 12 - Luggage and Porter Services.pdf"                            "$OUT/front-office/pdf/en/ch12-luggage.pdf"

copy "$FO_PPT_FR/Chapitre 1 - Introduction au manuel des procédures du front office.pptx" "$OUT/front-office/pptx/fr/ch01-introduction.pptx"
copy "$FO_PPT_FR/Chapitre 2 - Procédure de check-in.pptx"                                 "$OUT/front-office/pptx/fr/ch02-check-in.pptx"
copy "$FO_PPT_FR/Chapitre 3 - Procédure de check-out.pptx"                                "$OUT/front-office/pptx/fr/ch03-check-out.pptx"
copy "$FO_PPT_FR/Chapitre 4 - Communication client.pptx"                                  "$OUT/front-office/pptx/fr/ch04-communication-client.pptx"
copy "$FO_PPT_FR/Chapitre 5 - Techniques d'upselling.pptx"                                "$OUT/front-office/pptx/fr/ch05-upselling.pptx"
copy "$FO_PPT_FR/Chapitre 6 - Systèmes et opérations PMS.pptx"                            "$OUT/front-office/pptx/fr/ch06-pms.pptx"
copy "$FO_PPT_FR/Chapitre 7 - Night Audit.pptx"                                           "$OUT/front-office/pptx/fr/ch07-night-audit.pptx"
copy "$FO_PPT_FR/Chapitre 8 - Management de l'équipe.pptx"                                "$OUT/front-office/pptx/fr/ch08-management.pptx"
copy "$FO_PPT_FR/Chapitre 9 - Procédures d'urgence.pptx"                                  "$OUT/front-office/pptx/fr/ch09-urgence.pptx"
copy "$FO_PPT_FR/Chapitre 10 - Excellence et normes de qualité.pptx"                      "$OUT/front-office/pptx/fr/ch10-excellence.pptx"
copy "$FO_PPT_FR/Chapitre 11 - Concierge et services clients.pptx"                        "$OUT/front-office/pptx/fr/ch11-concierge.pptx"
copy "$FO_PPT_FR/Chapitre 12 - Bagagistes et portiers.pptx"                               "$OUT/front-office/pptx/fr/ch12-bagagistes.pptx"

copy "$FO_PPT_EN/Chapter 1 - Introduction to Front Office Procedures.pptx"                "$OUT/front-office/pptx/en/ch01-introduction.pptx"
copy "$FO_PPT_EN/Chapter 2 - Check-in Procedure.pptx"                                     "$OUT/front-office/pptx/en/ch02-check-in.pptx"
copy "$FO_PPT_EN/Chapter 3 - Check-out Procedure.pptx"                                    "$OUT/front-office/pptx/en/ch03-check-out.pptx"
copy "$FO_PPT_EN/Chapter 4 - Guest Communication.pptx"                                    "$OUT/front-office/pptx/en/ch04-guest-communication.pptx"
copy "$FO_PPT_EN/Chapter 5 - Upselling Techniques.pptx"                                   "$OUT/front-office/pptx/en/ch05-upselling.pptx"
copy "$FO_PPT_EN/Chapter 6 - Systems and PMS Operations.pptx"                             "$OUT/front-office/pptx/en/ch06-pms.pptx"
copy "$FO_PPT_EN/Chapter 7 - Night Audit.pptx"                                            "$OUT/front-office/pptx/en/ch07-night-audit.pptx"
copy "$FO_PPT_EN/Chapter 8 - Team Management.pptx"                                        "$OUT/front-office/pptx/en/ch08-management.pptx"
copy "$FO_PPT_EN/Chapter 9 - Emergency Procedures.pptx"                                   "$OUT/front-office/pptx/en/ch09-emergency.pptx"
copy "$FO_PPT_EN/Chapter 10 - Excellence and Quality Standards.pptx"                      "$OUT/front-office/pptx/en/ch10-excellence.pptx"
copy "$FO_PPT_EN/Chapter 11 - Concierge and Guest Services.pptx"                          "$OUT/front-office/pptx/en/ch11-concierge.pptx"
copy "$FO_PPT_EN/Chapter 12 - Luggage and Porter Services.pptx"                           "$OUT/front-office/pptx/en/ch12-luggage.pptx"

# ─── HOUSEKEEPING ─────────────────────────────────────────────────────────────
echo ""
echo "🛏️  Housekeeping..."

HSK_PDF_FR="$DRIVE/Playbook HSK/PDF/FR"
HSK_PDF_EN="$DRIVE/Playbook HSK/PDF/EN"
HSK_PPT_FR="$DRIVE/Playbook HSK/PPT/FR"
HSK_PPT_EN="$DRIVE/Playbook HSK/PPT/EN"

copy "$HSK_PDF_FR/Chapitre 1 - Introduction-a-lexcellence-du-housekeeping.pdf"            "$OUT/housekeeping/pdf/fr/ch01-introduction.pdf"
copy "$HSK_PDF_FR/Chapitre 2 - Standards-and-procedures-de-nettoyage-des-chambres.pdf"    "$OUT/housekeeping/pdf/fr/ch02-nettoyage-chambres.pdf"
copy "$HSK_PDF_FR/Chapitre 3 - Service-du-soir-and-Turndown.pdf"                          "$OUT/housekeeping/pdf/fr/ch03-turndown.pdf"
copy "$HSK_PDF_FR/Chapitre 4 - Parties-communes-et-nettoyage-specialise.pdf"              "$OUT/housekeeping/pdf/fr/ch04-parties-communes.pdf"
copy "$HSK_PDF_FR/Chapitre 5 - Services-aux-clients-et-interactions.pdf"                  "$OUT/housekeeping/pdf/fr/ch05-services-clients.pdf"
copy "$HSK_PDF_FR/Chapitre 6 - Controle-qualite-and-inspections.pdf"                      "$OUT/housekeeping/pdf/fr/ch06-controle-qualite.pdf"
copy "$HSK_PDF_FR/Chapitre 7 - Gestion-des-stocks-and-approvisionnements.pdf"             "$OUT/housekeeping/pdf/fr/ch07-stocks.pdf"
copy "$HSK_PDF_FR/Chapitre 8 - Management-des-equipes-and-planification.pdf"              "$OUT/housekeeping/pdf/fr/ch08-management.pdf"
copy "$HSK_PDF_FR/Chapitre 9 - Sante-securite-and-conformite.pdf"                         "$OUT/housekeeping/pdf/fr/ch09-sante-securite.pdf"
copy "$HSK_PDF_FR/Chapitre 10 - Developpement-durable-et-bonnes-pratiques.pdf"            "$OUT/housekeeping/pdf/fr/ch10-developpement-durable.pdf"

copy "$HSK_PDF_EN/Chapter 1 - Introduction-to-Housekeeping-Excellence.pdf"                "$OUT/housekeeping/pdf/en/ch01-introduction.pdf"
copy "$HSK_PDF_EN/Chapter 2 - Room-cleaning-standards-and-procedures.pdf"                 "$OUT/housekeeping/pdf/en/ch02-room-cleaning.pdf"
copy "$HSK_PDF_EN/Chapter 3 - Turndown-and-evening-service.pdf"                           "$OUT/housekeeping/pdf/en/ch03-turndown.pdf"
copy "$HSK_PDF_EN/Chapter 4 - Public-Areas-and-Specialty-Cleaning.pdf"                   "$OUT/housekeeping/pdf/en/ch04-public-areas.pdf"
copy "$HSK_PDF_EN/Chapter 5 - Guest-Services-and-Interaction.pdf"                         "$OUT/housekeeping/pdf/en/ch05-guest-services.pdf"
copy "$HSK_PDF_EN/Chapter 6 - Quality-control-and-inspections.pdf"                        "$OUT/housekeeping/pdf/en/ch06-quality-control.pdf"
copy "$HSK_PDF_EN/Chapter 7 - Inventory-and-Supplies-Management.pdf"                      "$OUT/housekeeping/pdf/en/ch07-inventory.pdf"
copy "$HSK_PDF_EN/Chapter 8 - Team-Management-and-Scheduling.pdf"                         "$OUT/housekeeping/pdf/en/ch08-management.pdf"
copy "$HSK_PDF_EN/Chapter 9 - Health-Safety-and-Compliance.pdf"                           "$OUT/housekeeping/pdf/en/ch09-health-safety.pdf"
copy "$HSK_PDF_EN/Chapter 10 - Sustainability-and-Best-Practices.pdf"                     "$OUT/housekeeping/pdf/en/ch10-sustainability.pdf"

copy "$HSK_PPT_FR/Chapitre 1 - Introduction-a-lexcellence-du-housekeeping.pptx"           "$OUT/housekeeping/pptx/fr/ch01-introduction.pptx"
copy "$HSK_PPT_FR/Chapitre 2 - Standards-and-procedures-de-nettoyage-des-chambres.pptx"   "$OUT/housekeeping/pptx/fr/ch02-nettoyage-chambres.pptx"
copy "$HSK_PPT_FR/Chapitre 3 - Service-du-soir-and-Turndown.pptx"                         "$OUT/housekeeping/pptx/fr/ch03-turndown.pptx"
copy "$HSK_PPT_FR/Chapitre 4 - Parties-communes-et-nettoyage-specialise.pptx"             "$OUT/housekeeping/pptx/fr/ch04-parties-communes.pptx"
copy "$HSK_PPT_FR/Chapitre 5 - Services-aux-clients-et-interactions.pptx"                 "$OUT/housekeeping/pptx/fr/ch05-services-clients.pptx"
copy "$HSK_PPT_FR/Chapitre 6 - Controle-qualite-and-inspections.pptx"                     "$OUT/housekeeping/pptx/fr/ch06-controle-qualite.pptx"
copy "$HSK_PPT_FR/Chapitre 7 - Gestion-des-stocks-and-approvisionnements.pptx"            "$OUT/housekeeping/pptx/fr/ch07-stocks.pptx"
copy "$HSK_PPT_FR/Chapitre 8 - Management-des-equipes-and-planification.pptx"             "$OUT/housekeeping/pptx/fr/ch08-management.pptx"
copy "$HSK_PPT_FR/Chapitre 9 - Sante-securite-and-conformite.pptx"                        "$OUT/housekeeping/pptx/fr/ch09-sante-securite.pptx"
copy "$HSK_PPT_FR/Chapitre 10 - Developpement-durable-et-bonnes-pratiques.pptx"           "$OUT/housekeeping/pptx/fr/ch10-developpement-durable.pptx"

copy "$HSK_PPT_EN/Chapter 1 - Introduction-to-Housekeeping-Excellence.pptx"               "$OUT/housekeeping/pptx/en/ch01-introduction.pptx"
copy "$HSK_PPT_EN/Chapter 2 - Room-cleaning-standards-and-procedures.pptx"                "$OUT/housekeeping/pptx/en/ch02-room-cleaning.pptx"
copy "$HSK_PPT_EN/Chapter 3 - Turndown-and-evening-service.pptx"                          "$OUT/housekeeping/pptx/en/ch03-turndown.pptx"
copy "$HSK_PPT_EN/Chapter 4 - Public-Areas-and-Specialty-Cleaning.pptx"                  "$OUT/housekeeping/pptx/en/ch04-public-areas.pptx"
copy "$HSK_PPT_EN/Chapter 5 - Guest-Services-and-Interaction.pptx"                        "$OUT/housekeeping/pptx/en/ch05-guest-services.pptx"
copy "$HSK_PPT_EN/Chapter 6 - Quality-control-and-inspections.pptx"                       "$OUT/housekeeping/pptx/en/ch06-quality-control.pptx"
copy "$HSK_PPT_EN/Chapter 7 - Inventory-and-Supplies-Management.pptx"                     "$OUT/housekeeping/pptx/en/ch07-inventory.pptx"
copy "$HSK_PPT_EN/Chapter 8 - Team-Management-and-Scheduling.pptx"                        "$OUT/housekeeping/pptx/en/ch08-management.pptx"
copy "$HSK_PPT_EN/Chapter 9 - Health-Safety-and-Compliance.pptx"                          "$OUT/housekeeping/pptx/en/ch09-health-safety.pptx"
copy "$HSK_PPT_EN/Chapter 10 - Sustainability-and-Best-Practices.pptx"                    "$OUT/housekeeping/pptx/en/ch10-sustainability.pptx"

# ─── F&B ──────────────────────────────────────────────────────────────────────
echo ""
echo "🍽️  F&B..."

FB_PDF_FR="$DRIVE/Playbook F&B/PDF/FR"
FB_PDF_EN="$DRIVE/Playbook F&B/PDF/EN"
FB_PPT_FR="$DRIVE/Playbook F&B/PPT/FR"
FB_PPT_EN="$DRIVE/Playbook F&B/PPT/EN"

copy "$FB_PDF_FR/Chapitre 1 - L'Art de l'excellence F&B.pdf"                              "$OUT/fb/pdf/fr/ch01-excellence.pdf"
copy "$FB_PDF_FR/Chapitre 2 - Séquence de service en restaurant.pdf"                      "$OUT/fb/pdf/fr/ch02-service-restaurant.pdf"
copy "$FB_PDF_FR/Chapitre 3 - Le service du petit-déjeuner.pdf"                           "$OUT/fb/pdf/fr/ch03-petit-dejeuner.pdf"
copy "$FB_PDF_FR/Chapitre 4 - Bar et service des boissons.pdf"                            "$OUT/fb/pdf/fr/ch04-bar.pdf"
copy "$FB_PDF_FR/Chapitre 5 - Excellence du service du vin.pdf"                           "$OUT/fb/pdf/fr/ch05-vin.pdf"
copy "$FB_PDF_FR/Chapitre 6 - Room service.pdf"                                           "$OUT/fb/pdf/fr/ch06-room-service.pdf"
copy "$FB_PDF_FR/Chapitre 7 - Interaction client et gestion des réclamations.pdf"         "$OUT/fb/pdf/fr/ch07-interaction-client.pdf"
copy "$FB_PDF_FR/Chapitre 8 - Mise en place et gestion des stations.pdf"                  "$OUT/fb/pdf/fr/ch08-mise-en-place.pdf"
copy "$FB_PDF_FR/Chapitre 9 - Gestion de l'équipe et opérations.pdf"                     "$OUT/fb/pdf/fr/ch09-management.pdf"
copy "$FB_PDF_FR/Chapitre 10 - Standards qualité et conformité.pdf"                       "$OUT/fb/pdf/fr/ch10-qualite.pdf"

copy "$FB_PDF_EN/Chapter 1 - The Art of F&B Excellence.pdf"                               "$OUT/fb/pdf/en/ch01-excellence.pdf"
copy "$FB_PDF_EN/Chapter 2 - Restaurant Service Standards.pdf"                            "$OUT/fb/pdf/en/ch02-service-restaurant.pdf"
copy "$FB_PDF_EN/Chapter 3 - Breakfast Service.pdf"                                       "$OUT/fb/pdf/en/ch03-breakfast.pdf"
copy "$FB_PDF_EN/Chapter 4 - Bar and Beverage Service.pdf"                                "$OUT/fb/pdf/en/ch04-bar.pdf"
copy "$FB_PDF_EN/Chapter 5 - Wine Service Excellence.pdf"                                 "$OUT/fb/pdf/en/ch05-wine.pdf"
copy "$FB_PDF_EN/Chapter 6 - Room Service - In Room Dining.pdf"                           "$OUT/fb/pdf/en/ch06-room-service.pdf"
copy "$FB_PDF_EN/Chapter 7 - Guest Interaction and Service Recovery.pdf"                  "$OUT/fb/pdf/en/ch07-guest-interaction.pdf"
copy "$FB_PDF_EN/Chapter 8 - Mise en Place and Station Management.pdf"                    "$OUT/fb/pdf/en/ch08-mise-en-place.pdf"
copy "$FB_PDF_EN/Chapter 9 - Team Management and Operations.pdf"                          "$OUT/fb/pdf/en/ch09-management.pdf"
copy "$FB_PDF_EN/Chapter 10 - Quality Standards and Compliance.pdf"                       "$OUT/fb/pdf/en/ch10-quality.pdf"

copy "$FB_PPT_FR/Chapitre 1 - L'Art de l'excellence F&B.pptx"                             "$OUT/fb/pptx/fr/ch01-excellence.pptx"
copy "$FB_PPT_FR/Chapitre 2 - Séquence de service en restaurant.pptx"                     "$OUT/fb/pptx/fr/ch02-service-restaurant.pptx"
copy "$FB_PPT_FR/Chapitre 3 - Le service du petit-déjeuner.pptx"                          "$OUT/fb/pptx/fr/ch03-petit-dejeuner.pptx"
copy "$FB_PPT_FR/Chapitre 4 - Bar et service des boissons.pptx"                           "$OUT/fb/pptx/fr/ch04-bar.pptx"
copy "$FB_PPT_FR/Chapitre 5 - Excellence du service du vin.pptx"                          "$OUT/fb/pptx/fr/ch05-vin.pptx"
copy "$FB_PPT_FR/Chapitre 6 - Room service.pptx"                                          "$OUT/fb/pptx/fr/ch06-room-service.pptx"
copy "$FB_PPT_FR/Chapitre 7 - Interaction client et gestion des réclamations.pptx"        "$OUT/fb/pptx/fr/ch07-interaction-client.pptx"
copy "$FB_PPT_FR/Chapitre 8 - Mise en place et gestion des stations.pptx"                 "$OUT/fb/pptx/fr/ch08-mise-en-place.pptx"
copy "$FB_PPT_FR/Chapitre 9 - Gestion de l'équipe et opérations.pptx"                    "$OUT/fb/pptx/fr/ch09-management.pptx"
copy "$FB_PPT_FR/Chapitre 10 - Standards qualité et conformité.pptx"                      "$OUT/fb/pptx/fr/ch10-qualite.pptx"

copy "$FB_PPT_EN/Chapter 1 - The Art of F&B Excellence.pptx"                              "$OUT/fb/pptx/en/ch01-excellence.pptx"
copy "$FB_PPT_EN/Chapter 2 - Restaurant Service Standards.pptx"                           "$OUT/fb/pptx/en/ch02-service-restaurant.pptx"
copy "$FB_PPT_EN/Chapter 3 - Breakfast Service.pptx"                                      "$OUT/fb/pptx/en/ch03-breakfast.pptx"
copy "$FB_PPT_EN/Chapter 4 - Bar and Beverage Service.pptx"                               "$OUT/fb/pptx/en/ch04-bar.pptx"
copy "$FB_PPT_EN/Chapter 5 - Wine Service Excellence.pptx"                                "$OUT/fb/pptx/en/ch05-wine.pptx"
copy "$FB_PPT_EN/Chapter 6 - Room Service - In Room Dining.pptx"                          "$OUT/fb/pptx/en/ch06-room-service.pptx"
copy "$FB_PPT_EN/Chapter 7 - Guest Interaction and Service Recovery.pptx"                 "$OUT/fb/pptx/en/ch07-guest-interaction.pptx"
copy "$FB_PPT_EN/Chapter 8 - Mise en Place and Station Management.pptx"                   "$OUT/fb/pptx/en/ch08-mise-en-place.pptx"
copy "$FB_PPT_EN/Chapter 9 - Team Management and Operations.pptx"                         "$OUT/fb/pptx/en/ch09-management.pptx"
copy "$FB_PPT_EN/Chapter 10 - Quality Standards and Compliance.pptx"                      "$OUT/fb/pptx/en/ch10-quality.pptx"

# ─── SPA & WELLNESS ───────────────────────────────────────────────────────────
echo ""
echo "💆 Spa & Wellness..."

SPA_PDF_FR="$DRIVE/Playbook SPA/PDF/FR"
SPA_PDF_EN="$DRIVE/Playbook SPA/PDF/EN"
SPA_PPT_FR="$DRIVE/Playbook SPA/PPT/FR"
SPA_PPT_EN="$DRIVE/Playbook SPA/PPT/EN"

copy "$SPA_PDF_FR/Chapitre 1 - Introduction-a-lExcellence-du-Spa-and-Bien-Etre.pdf"       "$OUT/spa/pdf/fr/ch01-introduction.pdf"
copy "$SPA_PDF_FR/Chapitre 2 - Standards-and-Preparation-de-la-Salle-de-Soins.pdf"        "$OUT/spa/pdf/fr/ch02-salle-soins.pdf"
copy "$SPA_PDF_FR/Chapitre 3 - Le-parcours-client-et-les-protocoles-de-service.pdf"       "$OUT/spa/pdf/fr/ch03-parcours-client.pdf"
copy "$SPA_PDF_FR/Chapitre 4 - Carte-de-soins-et-techniques.pdf"                          "$OUT/spa/pdf/fr/ch04-carte-soins.pdf"
copy "$SPA_PDF_FR/Chapitre 5 - Connaissance-produit-et-vente-retail.pdf"                  "$OUT/spa/pdf/fr/ch05-retail.pdf"
copy "$SPA_PDF_FR/Chapitre 6 - Gestion-des-installations-et-des-equipements-spa.pdf"      "$OUT/spa/pdf/fr/ch06-installations.pdf"
copy "$SPA_PDF_FR/Chapitre 7 - Gestion-de-lequipe-et-planification.pdf"                   "$OUT/spa/pdf/fr/ch07-management.pdf"
copy "$SPA_PDF_FR/Chapitre 8 - Controle-qualite-et-satisfaction-client.pdf"               "$OUT/spa/pdf/fr/ch08-qualite.pdf"
copy "$SPA_PDF_FR/Chapitre 9 - Standards-professionnels-et-presentation.pdf"              "$OUT/spa/pdf/fr/ch09-standards-pro.pdf"

copy "$SPA_PDF_EN/Chapter 1 - Introduction-to-Spa-and-Wellness-Excellence.pdf"            "$OUT/spa/pdf/en/ch01-introduction.pdf"
copy "$SPA_PDF_EN/Chapter 2 - Treatment-Room-Standards.pdf"                               "$OUT/spa/pdf/en/ch02-treatment-room.pdf"
copy "$SPA_PDF_EN/Chapter 3 - The-Guest-Journey-and-Service-Protocol.pdf"                 "$OUT/spa/pdf/en/ch03-guest-journey.pdf"
copy "$SPA_PDF_EN/Chapter 4 - Treatment-menu-and-techniques.pdf"                          "$OUT/spa/pdf/en/ch04-treatment-menu.pdf"
copy "$SPA_PDF_EN/Chapter 5 - Product-Knowledge-and-Retail.pdf"                           "$OUT/spa/pdf/en/ch05-retail.pdf"
copy "$SPA_PDF_EN/Chapter 6 - Spa-Facilities-and-Amenities-Management.pdf"                "$OUT/spa/pdf/en/ch06-facilities.pdf"
copy "$SPA_PDF_EN/Chapter 7 - Team-Management-and-Scheduling.pdf"                         "$OUT/spa/pdf/en/ch07-management.pdf"
copy "$SPA_PDF_EN/Chapter 8 - Quality-Control-and-Guest-Satisfaction.pdf"                 "$OUT/spa/pdf/en/ch08-quality.pdf"
copy "$SPA_PDF_EN/Chapter 9 - Professional-Standards-and-Grooming.pdf"                    "$OUT/spa/pdf/en/ch09-standards-pro.pdf"

copy "$SPA_PPT_FR/Chapitre 1 - Introduction-a-lExcellence-du-Spa-and-Bien-Etre.pptx"     "$OUT/spa/pptx/fr/ch01-introduction.pptx"
copy "$SPA_PPT_FR/Chapitre 2 - Standards-and-Preparation-de-la-Salle-de-Soins.pptx"      "$OUT/spa/pptx/fr/ch02-salle-soins.pptx"
copy "$SPA_PPT_FR/Chapitre 3 - Le-parcours-client-et-les-protocoles-de-service.pptx"     "$OUT/spa/pptx/fr/ch03-parcours-client.pptx"
copy "$SPA_PPT_FR/Chapitre 4 - Carte-de-soins-et-techniques.pptx"                        "$OUT/spa/pptx/fr/ch04-carte-soins.pptx"
copy "$SPA_PPT_FR/Chapitre 5 - Connaissance-produit-et-vente-retail.pptx"                "$OUT/spa/pptx/fr/ch05-retail.pptx"
copy "$SPA_PPT_FR/Chapitre 6 - Gestion-des-installations-et-des-equipements-spa.pptx"    "$OUT/spa/pptx/fr/ch06-installations.pptx"
copy "$SPA_PPT_FR/Chapitre 7 - Gestion-de-lequipe-et-planification.pptx"                 "$OUT/spa/pptx/fr/ch07-management.pptx"
copy "$SPA_PPT_FR/Chapitre 8 - Controle-qualite-et-satisfaction-client.pptx"             "$OUT/spa/pptx/fr/ch08-qualite.pptx"
copy "$SPA_PPT_FR/Chapitre 9 - Standards-professionnels-et-presentation.pptx"            "$OUT/spa/pptx/fr/ch09-standards-pro.pptx"

copy "$SPA_PPT_EN/Chapter 1 - Introduction-to-Spa-and-Wellness-Excellence.pptx"          "$OUT/spa/pptx/en/ch01-introduction.pptx"
copy "$SPA_PPT_EN/Chapter 2 - Treatment-Room-Standards.pptx"                             "$OUT/spa/pptx/en/ch02-treatment-room.pptx"
copy "$SPA_PPT_EN/Chapter 3 - The-Guest-Journey-and-Service-Protocol.pptx"               "$OUT/spa/pptx/en/ch03-guest-journey.pptx"
copy "$SPA_PPT_EN/Chapter 4 - Treatment-menu-and-techniques.pptx"                        "$OUT/spa/pptx/en/ch04-treatment-menu.pptx"
copy "$SPA_PPT_EN/Chapter 5 - Product-Knowledge-and-Retail.pptx"                         "$OUT/spa/pptx/en/ch05-retail.pptx"
copy "$SPA_PPT_EN/Chapter 6 - Spa-Facilities-and-Amenities-Management.pptx"              "$OUT/spa/pptx/en/ch06-facilities.pptx"
copy "$SPA_PPT_EN/Chapter 7 - Team-Management-and-Scheduling.pptx"                       "$OUT/spa/pptx/en/ch07-management.pptx"
copy "$SPA_PPT_EN/Chapter 8 - Quality-Control-and-Guest-Satisfaction.pptx"               "$OUT/spa/pptx/en/ch08-quality.pptx"
copy "$SPA_PPT_EN/Chapter 9 - Professional-Standards-and-Grooming.pptx"                  "$OUT/spa/pptx/en/ch09-standards-pro.pptx"

echo ""
echo "✅ Terminé ! Fichiers prêts dans : $OUT"
echo ""
echo "Structure créée :"
find "$OUT" -type d | sort
